services:
  promo-bot:
    build: .
    container_name: promo-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - promo-network

  redis:
    image: public.ecr.aws/docker/library/redis:7-alpine
    container_name: promo-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - promo-network

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - promo-network

volumes:
  redis-data:


networks:
  promo-network:
    driver: bridge
