// Catálogo curado. Regras que valem para toda receita aqui:
//   ≤ 8 ingredientes, ingrediente de mercado brasileiro comum, medida em
//   xícara/colher/"a gosto", passo curto (um por tela no modo cozinha).
// O alvo principal é o casal na quarta às 20h com fome — por isso a maioria
// fica em 30 min.
//
// Mas existe o prato de sábado: lasanha e parmegiana levam mais de uma hora e
// mentir no tempo pra caber numa regra seria pior do que não ter a receita —
// o casal descobre a mentira com fome, na cozinha. Quem separa os dois mundos
// é a roda: acima de 45 min a receita já perde peso em dia de semana, e
// dificuldade 2 ganha peso no fim de semana. A regra virou tag, não corte.
//
// `contem` alimenta as restrições (filtro duro na roda) e o alerta de alérgeno.
// `tags` alimenta a ponderação por hora/dia/clima.

const i = (nome, medida, opcional = false) => ({ nome, medida, opcional });

export const RECEITAS = [
  {
    id: 'carbonara-rapida',
    titulo: 'Carbonara de quarta',
    tempoMin: 15, dificuldade: 1, custo: 18, porcoes: 2,
    tags: ['jantar', 'almoco', 'rapido', 'comfort'],
    contem: ['gluten', 'ovo', 'lactose', 'carne'],
    ingredientes: [i('macarrão', '250 g'), i('ovo', '2 unidades'), i('bacon', '100 g'),
      i('queijo parmesão', '½ xícara'), i('sal', 'a gosto'), i('pimenta do reino', 'a gosto')],
    passos: [
      { texto: 'Ponha água pra ferver com bastante sal.', timerSeg: 0 },
      { texto: 'Cozinhe o macarrão pelo tempo do pacote.', timerSeg: 600 },
      { texto: 'Frite o bacon em fogo médio até dourar. Desligue o fogo.', timerSeg: 300 },
      { texto: 'Bata os ovos com o queijo e uma pitada de pimenta.' },
      { texto: 'Junte o macarrão quente ao bacon, fora do fogo, e misture os ovos rápido — o calor cozinha sem virar omelete.' },
      { texto: 'Se secar, uma colher da água do macarrão resolve. Prove o sal e sirva.' },
    ],
  },
  {
    id: 'arroz-carreteiro',
    titulo: 'Arroz de carreteiro de sobra',
    tempoMin: 25, dificuldade: 1, custo: 15, porcoes: 2,
    tags: ['jantar', 'almoco', 'sobras', 'comfort'],
    contem: ['carne'],
    ingredientes: [i('arroz', '1 xícara (cru)'), i('carne moída', '300 g'), i('cebola', '1 unidade'),
      i('alho', '2 dentes'), i('tomate', '1 unidade'), i('cheiro verde', 'a gosto', true), i('sal', 'a gosto')],
    passos: [
      { texto: 'Refogue a cebola e o alho no óleo até ficarem transparentes.', timerSeg: 180 },
      { texto: 'Junte a carne moída e mexa até soltar e dourar.', timerSeg: 420 },
      { texto: 'Acrescente o tomate picado e deixe murchar.', timerSeg: 180 },
      { texto: 'Adicione o arroz cru, misture bem e cubra com 2 xícaras de água quente.' },
      { texto: 'Tampe e cozinhe em fogo baixo até secar.', timerSeg: 900 },
      { texto: 'Solte com o garfo, jogue o cheiro verde e sirva.' },
    ],
  },
  {
    id: 'frango-limao',
    titulo: 'Frango na frigideira com limão',
    tempoMin: 20, dificuldade: 1, custo: 22, porcoes: 2,
    tags: ['jantar', 'almoco', 'leve', 'rapido'],
    contem: ['carne'],
    ingredientes: [i('frango', '2 filés'), i('limão', '1 unidade'), i('alho', '2 dentes'),
      i('azeite', '2 colheres de sopa'), i('sal', 'a gosto'), i('pimenta do reino', 'a gosto')],
    passos: [
      { texto: 'Tempere o frango com sal, pimenta, alho amassado e o suco de meio limão. Deixe pegar gosto.', timerSeg: 300 },
      { texto: 'Aqueça a frigideira com azeite até quase fumaçar.' },
      { texto: 'Doure de um lado sem mexer.', timerSeg: 300 },
      { texto: 'Vire, tampe e deixe cozinhar por dentro.', timerSeg: 360 },
      { texto: 'Termine com o resto do limão e sirva com arroz ou salada.' },
    ],
  },
  {
    id: 'omelete-recheado',
    titulo: 'Omelete que salva a noite',
    tempoMin: 10, dificuldade: 1, custo: 8, porcoes: 1,
    tags: ['jantar', 'cafe', 'madrugada', 'rapido'],
    contem: ['ovo', 'lactose'],
    ingredientes: [i('ovo', '3 unidades'), i('queijo', '2 fatias'), i('tomate', '½ unidade', true),
      i('cebolinha', 'a gosto', true), i('sal', 'a gosto')],
    passos: [
      { texto: 'Bata os ovos com um garfo e uma pitada de sal — 20 segundos bastam.' },
      { texto: 'Frigideira em fogo médio-baixo com um fio de óleo.' },
      { texto: 'Jogue os ovos e espere as bordas firmarem.', timerSeg: 120 },
      { texto: 'Ponha o queijo de um lado, dobre e desligue. O vapor derrete.' },
    ],
  },
  {
    id: 'macarrao-alho-oleo',
    titulo: 'Alho e óleo honesto',
    tempoMin: 15, dificuldade: 1, custo: 10, porcoes: 2,
    tags: ['jantar', 'rapido', 'madrugada', 'barato'],
    contem: ['gluten'],
    ingredientes: [i('macarrão', '250 g'), i('alho', '4 dentes'), i('azeite', '4 colheres de sopa'),
      i('pimenta calabresa', 'a gosto', true), i('sal', 'a gosto'), i('queijo parmesão', 'a gosto', true)],
    passos: [
      { texto: 'Água fervendo com sal, macarrão dentro.', timerSeg: 600 },
      { texto: 'Enquanto cozinha, doure o alho fatiado no azeite em fogo baixo — dourado claro, não escuro.', timerSeg: 240 },
      { texto: 'Junte o macarrão escorrido com meia xícara da água do cozimento.' },
      { texto: 'Mexa até virar molho. Queijo por cima se tiver.' },
    ],
  },
  {
    id: 'sopa-legumes',
    titulo: 'Sopa de legumes de dia frio',
    tempoMin: 35, dificuldade: 1, custo: 14, porcoes: 3,
    tags: ['jantar', 'sopa', 'comfort', 'leve'],
    contem: [],
    ingredientes: [i('batata', '2 unidades'), i('cenoura', '2 unidades'), i('cebola', '1 unidade'),
      i('alho', '2 dentes'), i('macarrão', '½ xícara', true), i('sal', 'a gosto')],
    passos: [
      { texto: 'Refogue cebola e alho até perfumar.', timerSeg: 180 },
      { texto: 'Junte batata e cenoura em cubos e cubra com água (uns 4 dedos acima).' },
      { texto: 'Cozinhe até o garfo entrar fácil na batata.', timerSeg: 1200 },
      { texto: 'Se quiser mais corpo, amasse metade dos legumes com o garfo.' },
      { texto: 'Macarrão nos últimos minutos, se for usar.', timerSeg: 420 },
    ],
  },
  {
    id: 'strogonoff-frango',
    titulo: 'Estrogonofe de frango',
    tempoMin: 30, dificuldade: 2, custo: 28, porcoes: 3,
    tags: ['jantar', 'almoco', 'comfort'],
    contem: ['carne', 'lactose'],
    ingredientes: [i('frango', '500 g'), i('creme de leite', '1 lata'), i('molho de tomate', '1 xícara'),
      i('cebola', '1 unidade'), i('mostarda', '1 colher de sopa'), i('champignon', '1 pote', true), i('sal', 'a gosto')],
    passos: [
      { texto: 'Corte o frango em cubos e tempere com sal e pimenta.' },
      { texto: 'Doure em fogo alto, sem mexer muito, até pegar cor.', timerSeg: 480 },
      { texto: 'Junte a cebola picada e deixe murchar.', timerSeg: 240 },
      { texto: 'Molho de tomate e mostarda; ferva devagar.', timerSeg: 300 },
      { texto: 'Fogo baixo, creme de leite por último — sem deixar ferver depois.' },
      { texto: 'Sirva com arroz e batata palha se tiver.' },
    ],
  },
  {
    id: 'panqueca-simples',
    titulo: 'Panqueca de liquidificador',
    tempoMin: 25, dificuldade: 1, custo: 12, porcoes: 2,
    tags: ['jantar', 'cafe', 'comfort'],
    contem: ['gluten', 'ovo', 'lactose'],
    ingredientes: [i('farinha de trigo', '1 xícara'), i('leite', '1 xícara'), i('ovo', '2 unidades'),
      i('queijo', 'a gosto'), i('molho de tomate', '1 xícara'), i('sal', 'a gosto')],
    passos: [
      { texto: 'Bata leite, ovos, farinha e sal no liquidificador até ficar liso.' },
      { texto: 'Frigideira antiaderente quente, uma concha de massa, espalhe girando.' },
      { texto: 'Quando soltar sozinha das bordas, vire.', timerSeg: 90 },
      { texto: 'Recheie com queijo, enrole e cubra com molho.' },
      { texto: 'Se quiser, gratine na frigideira tampada até derreter.', timerSeg: 180 },
    ],
  },
  {
    id: 'salada-grao',
    titulo: 'Salada de grão-de-bico',
    tempoMin: 12, dificuldade: 1, custo: 16, porcoes: 2,
    tags: ['almoco', 'jantar', 'leve', 'rapido'],
    contem: [],
    ingredientes: [i('grão-de-bico', '1 lata'), i('tomate', '2 unidades'), i('cebola', '½ unidade'),
      i('azeite', '3 colheres de sopa'), i('limão', '½ unidade'), i('salsa', 'a gosto', true), i('sal', 'a gosto')],
    passos: [
      { texto: 'Escorra e lave o grão-de-bico.' },
      { texto: 'Pique tomate e cebola em cubos pequenos.' },
      { texto: 'Misture tudo com azeite, limão e sal. Prove antes de servir.' },
      { texto: 'Fica melhor depois de 10 minutos na geladeira.', timerSeg: 600 },
    ],
  },
  {
    id: 'arroz-frito-sobras',
    titulo: 'Arroz frito de geladeira',
    tempoMin: 15, dificuldade: 1, custo: 9, porcoes: 2,
    tags: ['jantar', 'sobras', 'rapido', 'barato'],
    contem: ['ovo'],
    ingredientes: [i('arroz', '2 xícaras (cozido)'), i('ovo', '2 unidades'), i('cenoura', '1 unidade'),
      i('cebolinha', 'a gosto', true), i('shoyu', '2 colheres de sopa', true), i('alho', '2 dentes')],
    passos: [
      { texto: 'Frigideira bem quente com um fio de óleo — arroz frito precisa de fogo alto.' },
      { texto: 'Doure o alho, junte a cenoura em cubinhos.', timerSeg: 180 },
      { texto: 'Empurre pra um lado, quebre os ovos do outro e mexa até firmar.' },
      { texto: 'Junte o arroz e misture, apertando contra a frigideira.', timerSeg: 240 },
      { texto: 'Shoyu e cebolinha por último, fora do fogo.' },
    ],
  },
  {
    id: 'file-batata-forno',
    titulo: 'Frango e batata no forno',
    tempoMin: 40, dificuldade: 1, custo: 24, porcoes: 3,
    tags: ['jantar', 'forno', 'comfort'],
    contem: ['carne'],
    ingredientes: [i('frango', '4 sobrecoxas'), i('batata', '4 unidades'), i('alho', '4 dentes'),
      i('azeite', '3 colheres de sopa'), i('limão', '1 unidade'), i('sal', 'a gosto'), i('páprica', 'a gosto', true)],
    passos: [
      { texto: 'Forno a 200°C. Tempere frango e batata com tudo, na própria assadeira.' },
      { texto: 'Espalhe sem empilhar — empilhado cozinha no vapor em vez de dourar.' },
      { texto: 'Asse até a batata ficar macia.', timerSeg: 1500 },
      { texto: 'Suba o fogo nos últimos minutos pra dourar a pele.', timerSeg: 420 },
    ],
  },
  {
    id: 'sanduiche-quente',
    titulo: 'Misto quente de frigideira',
    tempoMin: 8, dificuldade: 1, custo: 7, porcoes: 1,
    tags: ['cafe', 'madrugada', 'rapido', 'barato'],
    contem: ['gluten', 'lactose', 'carne'],
    ingredientes: [i('pão de forma', '2 fatias'), i('queijo', '2 fatias'), i('presunto', '2 fatias'),
      i('manteiga', 'a gosto'), i('tomate', '2 rodelas', true)],
    passos: [
      { texto: 'Passe manteiga no lado de fora das duas fatias.' },
      { texto: 'Monte com queijo e presunto no meio.' },
      { texto: 'Frigideira em fogo baixo, prense com uma panela por cima.', timerSeg: 150 },
      { texto: 'Vire e repita até dourar. Corte na diagonal — é diferente, confie.' },
    ],
  },
  {
    id: 'feijao-tropeiro-rapido',
    titulo: 'Tropeiro de sobra de feijão',
    tempoMin: 20, dificuldade: 1, custo: 13, porcoes: 2,
    tags: ['almoco', 'jantar', 'sobras', 'comfort'],
    contem: ['ovo', 'carne'],
    ingredientes: [i('feijão', '2 xícaras (cozido)'), i('farinha de mandioca', '1 xícara'), i('ovo', '2 unidades'),
      i('linguiça', '200 g'), i('cebola', '1 unidade'), i('couve', 'a gosto', true), i('sal', 'a gosto')],
    passos: [
      { texto: 'Frite a linguiça em rodelas até soltar gordura.', timerSeg: 360 },
      { texto: 'Junte a cebola e deixe dourar nessa gordura.', timerSeg: 180 },
      { texto: 'Quebre os ovos direto na panela e mexa até firmar.' },
      { texto: 'Feijão escorrido, mistura, e só então a farinha aos poucos.' },
      { texto: 'Couve fatiada fina por último, fogo desligado.' },
    ],
  },
  {
    id: 'macarrao-atum',
    titulo: 'Macarrão de atum de armário',
    tempoMin: 18, dificuldade: 1, custo: 14, porcoes: 2,
    tags: ['jantar', 'rapido', 'barato'],
    contem: ['gluten', 'peixe'],
    ingredientes: [i('macarrão', '250 g'), i('atum', '1 lata'), i('molho de tomate', '1 xícara'),
      i('cebola', '½ unidade'), i('alho', '2 dentes'), i('azeitona', 'a gosto', true), i('sal', 'a gosto')],
    passos: [
      { texto: 'Macarrão na água fervente com sal.', timerSeg: 600 },
      { texto: 'Refogue cebola e alho, junte o atum escorrido.', timerSeg: 180 },
      { texto: 'Molho de tomate, fogo baixo, deixe apurar.', timerSeg: 300 },
      { texto: 'Misture com o macarrão e as azeitonas.' },
    ],
  },
  {
    id: 'cuscuz-ovo',
    titulo: 'Cuscuz com ovo',
    tempoMin: 12, dificuldade: 1, custo: 6, porcoes: 1,
    tags: ['cafe', 'jantar', 'rapido', 'barato'],
    contem: ['ovo'],
    ingredientes: [i('flocão de milho', '1 xícara'), i('ovo', '2 unidades'), i('manteiga', 'a gosto'),
      i('sal', 'a gosto'), i('queijo coalho', 'a gosto', true)],
    passos: [
      { texto: 'Umedeça o flocão com ½ xícara de água e sal. Deixe descansar.', timerSeg: 300 },
      { texto: 'Cuscuzeira ou peneira sobre panela com água fervendo: 8 minutos no vapor.', timerSeg: 480 },
      { texto: 'Enquanto isso, faça os ovos do jeito que vocês gostam.' },
      { texto: 'Manteiga por cima do cuscuz quente e sirva com o ovo.' },
    ],
  },
  {
    id: 'legumes-forno-queijo',
    titulo: 'Legumes gratinados',
    tempoMin: 35, dificuldade: 1, custo: 18, porcoes: 2,
    tags: ['jantar', 'forno', 'leve'],
    contem: ['lactose'],
    ingredientes: [i('abobrinha', '1 unidade'), i('batata', '2 unidades'), i('tomate', '2 unidades'),
      i('queijo', '150 g'), i('azeite', '2 colheres de sopa'), i('sal', 'a gosto'), i('orégano', 'a gosto', true)],
    passos: [
      { texto: 'Forno a 200°C. Fatie tudo em rodelas de mesma espessura.' },
      { texto: 'Monte em camadas na travessa, temperando entre elas.' },
      { texto: 'Cubra com papel-alumínio e asse.', timerSeg: 1200 },
      { texto: 'Tire o papel, ponha o queijo e volte ao forno até gratinar.', timerSeg: 600 },
    ],
  },
  {
    id: 'lasanha-de-domingo',
    titulo: 'Lasanha de domingo',
    tempoMin: 70, dificuldade: 2, custo: 45, porcoes: 4,
    tags: ['jantar', 'almoco', 'forno', 'comfort'],
    contem: ['gluten', 'lactose', 'carne'],
    ingredientes: [i('massa de lasanha', '1 pacote'), i('carne moída', '500 g'), i('molho de tomate', '2 xícaras'),
      i('presunto', '200 g'), i('mussarela', '300 g'), i('cebola', '1 unidade'), i('alho', '3 dentes'),
      i('creme de leite', '1 lata', true)],
    passos: [
      { texto: 'Refogue a cebola e o alho, junte a carne moída e deixe dourar de verdade.', timerSeg: 480 },
      { texto: 'Molho de tomate na carne, fogo baixo, apurando até encorpar.', timerSeg: 600 },
      { texto: 'Molho no fundo da travessa antes de tudo — é o que impede a massa de grudar.' },
      { texto: 'Camadas: massa, carne, presunto, queijo. Repita até acabar.' },
      { texto: 'Termine com molho e uma camada boa de queijo: a de cima é a que aparece.' },
      { texto: 'Forno a 200°C coberto com papel-alumínio.', timerSeg: 1800 },
      { texto: 'Tire o papel e deixe gratinar até dourar.', timerSeg: 600 },
      { texto: 'Espere 10 minutos antes de cortar. Quente demais, ela desmonta no prato.', timerSeg: 600 },
    ],
  },
  {
    id: 'ramen-coreano',
    titulo: 'Ramen coreano turbinado',
    tempoMin: 15, dificuldade: 1, custo: 16, porcoes: 2,
    tags: ['jantar', 'rapido', 'madrugada', 'comfort'],
    contem: ['gluten', 'ovo'],
    ingredientes: [i('macarrão instantâneo coreano', '2 pacotes'), i('ovo', '2 unidades'),
      i('cebolinha', 'a gosto', true), i('queijo', '1 fatia', true), i('kimchi', 'a gosto', true),
      i('shoyu', '1 colher de sopa', true)],
    passos: [
      { texto: 'Água fervendo. Use um pouco menos do que o pacote manda — caldo concentrado é o ponto.' },
      { texto: 'Macarrão e o tempero do pacote juntos.', timerSeg: 300 },
      { texto: 'Quebre os ovos por cima sem mexer e tampe: eles cozinham no vapor.', timerSeg: 120 },
      { texto: 'Fogo desligado, a fatia de queijo por cima — derrete e tira o excesso de ardência.' },
      { texto: 'Cebolinha e kimchi na tigela, no fim. Kimchi cozido perde a graça.' },
    ],
  },
  {
    id: 'pasta-limone-salmao',
    titulo: 'Pasta al limone com salmão',
    tempoMin: 25, dificuldade: 2, custo: 55, porcoes: 2,
    tags: ['jantar', 'leve'],
    contem: ['gluten', 'lactose', 'peixe'],
    ingredientes: [i('macarrão', '250 g'), i('salmão', '300 g'), i('creme de leite', '1 caixa'),
      i('limão', '1 unidade'), i('alho', '2 dentes'), i('queijo parmesão', '½ xícara'), i('sal', 'a gosto')],
    passos: [
      { texto: 'Macarrão na água fervente com bastante sal. Guarde uma xícara da água antes de escorrer.', timerSeg: 600 },
      { texto: 'Salmão em cubos, sal, e sele na frigideira quente sem mexer muito.', timerSeg: 300 },
      { texto: 'Tire o salmão. No mesmo azeite, alho em fogo baixo só até perfumar.', timerSeg: 120 },
      { texto: 'Creme de leite, raspas e suco do limão (siciliano se tiver) e o parmesão, fora do fogo forte.' },
      { texto: 'Junte o macarrão e um pouco da água reservada até virar molho de verdade.' },
      { texto: 'Salmão de volta por último, só pra aquecer. Mexer demais desmancha.' },
    ],
  },
  {
    id: 'hamburguer-caseiro',
    titulo: 'Hambúrguer caseiro',
    tempoMin: 25, dificuldade: 1, custo: 32, porcoes: 2,
    tags: ['jantar', 'comfort'],
    contem: ['gluten', 'lactose', 'carne'],
    ingredientes: [i('carne moída', '400 g'), i('pão de hambúrguer', '2 unidades'), i('queijo', '2 fatias'),
      i('cebola', '1 unidade'), i('alface', 'a gosto', true), i('tomate', '1 unidade', true), i('sal', 'a gosto')],
    passos: [
      { texto: 'Divida a carne em duas bolas e achate com a mão. Não sove: carne sovada vira almôndega.' },
      { texto: 'Sal só do lado de fora, e só na hora de ir pra frigideira.' },
      { texto: 'Frigideira bem quente. Coloque e não mexa até formar crosta escura.', timerSeg: 180 },
      { texto: 'Vire uma vez só. Nada de apertar com a espátula — ali vai embora o suco.', timerSeg: 120 },
      { texto: 'Queijo em cima, tampe por meio minuto e desligue.', timerSeg: 30 },
      { texto: 'Toste os pães na mesma frigideira, na gordura que sobrou. Monte e coma em pé mesmo.' },
    ],
  },
  {
    id: 'hot-dog-caseiro',
    titulo: 'Hot dog de sexta',
    tempoMin: 20, dificuldade: 1, custo: 18, porcoes: 2,
    tags: ['jantar', 'madrugada', 'rapido', 'barato', 'comfort'],
    contem: ['gluten', 'carne'],
    ingredientes: [i('salsicha', '4 unidades'), i('pão de hot dog', '4 unidades'), i('molho de tomate', '1 xícara'),
      i('cebola', '½ unidade'), i('batata palha', 'a gosto', true), i('milho', 'a gosto', true)],
    passos: [
      { texto: 'Refogue a cebola picada, junte o molho de tomate e deixe apurar.', timerSeg: 300 },
      { texto: 'Salsichas inteiras no molho, fogo baixo, tampado — elas pegam gosto ali.', timerSeg: 420 },
      { texto: 'Quer o clássico? Desfie as salsichas dentro do molho com dois garfos.' },
      { texto: 'Aqueça os pães (forno, frigideira ou 15 s no micro-ondas dentro de um pano).' },
      { texto: 'Monte, cubra com molho e só então batata palha — ela precisa continuar crocante.' },
    ],
  },
  {
    id: 'parmegiana-de-forno',
    titulo: 'Parmegiana de sábado',
    tempoMin: 50, dificuldade: 2, custo: 42, porcoes: 3,
    tags: ['almoco', 'jantar', 'forno', 'comfort'],
    contem: ['gluten', 'ovo', 'lactose', 'carne'],
    ingredientes: [i('bife', '4 unidades'), i('farinha de rosca', '2 xícaras'), i('ovo', '2 unidades'),
      i('farinha de trigo', '1 xícara'), i('molho de tomate', '2 xícaras'), i('mussarela', '250 g'),
      i('sal', 'a gosto')],
    passos: [
      { texto: 'Bata os bifes com o fundo de uma panela até ficarem finos. Tempere com sal.' },
      { texto: 'Três pratos na ordem: farinha de trigo, ovo batido, farinha de rosca.' },
      { texto: 'Passe cada bife nos três, apertando bem na farinha de rosca.' },
      { texto: 'Frite em óleo quente até dourar dos dois lados. Escorra no papel.', timerSeg: 480 },
      { texto: 'Na travessa: molho no fundo, bifes por cima, mais molho, depois o queijo.' },
      { texto: 'Forno a 200°C só até o queijo derreter e borbulhar.', timerSeg: 900 },
    ],
  },
  {
    id: 'arroz-feijao-carne-vagem',
    titulo: 'Arroz, feijão e carne com vagem',
    tempoMin: 35, dificuldade: 1, custo: 26, porcoes: 3,
    tags: ['almoco', 'jantar', 'comfort'],
    contem: ['carne'],
    ingredientes: [i('arroz', '1 xícara (cru)'), i('feijão', '2 xícaras (cozido)'), i('carne moída', '400 g'),
      i('vagem', '200 g'), i('cebola', '1 unidade'), i('alho', '3 dentes'), i('tomate', '1 unidade', true),
      i('sal', 'a gosto')],
    passos: [
      { texto: 'Arroz primeiro: refogue metade do alho, junte o arroz e 2 xícaras de água quente.', timerSeg: 900 },
      { texto: 'Vagem em pedaços de dois dedos, na água fervente. Verde e firme, não murcha.', timerSeg: 240 },
      { texto: 'Na outra panela, cebola e o resto do alho até dourar.', timerSeg: 180 },
      { texto: 'Carne moída em fogo alto, espalhada, até soltar a água e começar a fritar.', timerSeg: 480 },
      { texto: 'Tomate picado, sal, e a vagem escorrida por último — ela só se junta, não cozinha de novo.' },
      { texto: 'Feijão esquentando ao lado. Sirva tudo junto, do jeito que é em casa.' },
    ],
  },
];

export const RECEITAS_POR_ID = Object.fromEntries(RECEITAS.map((r) => [r.id, r]));

// Ingredientes que o app conhece — alimenta o autocomplete da despensa.
export const INGREDIENTES_CONHECIDOS = [...new Set(
  RECEITAS.flatMap((r) => r.ingredientes.map((ing) => ing.nome)),
)].sort((a, b) => a.localeCompare(b, 'pt-BR'));
